### ISSUE TITLE
When opening the bml file in track_common.rho, the program crashes immediately

### ISSUE THREAD

**Issue by ghost** [xpoi5010/Kartrider-File-Reader#1]
![image](https://user-images.githubusercontent.com/19208884/106353602-ba462b80-6326-11eb-8f3a-148c394012c8.png)

**Comment by xpoi5010** [comment]
Because of the low performance of ucXmlRichTextBox, it will spend 297 seconds formatting XML strings. Therefore, I will stop using ucXmlRichTextBox and use new method to format xml strings.

New Method:
Convert bml to xml: 1.9948 ms
Format XML Strings: 2750.115 ms

![report002](https://user-images.githubusercontent.com/18278612/106360116-acf26680-6351-11eb-93c5-1a5e6ffb2087.png)
I will fix it on next release(Dev 21.1.5).
Thank you for reporting!

**Comment by xpoi5010** [comment]
This problem was fixed on Dev 22.3.1 version.
Thank you for reporting.
